<script setup lang="ts">
import { projectIndex, projectPath } from '../utils/project-links';
import { richText, embedSource } from "../utils/content";
import { computed, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { getData, getLanguageIso, resolveMediaUrl } from '../utils/api'
import { type CaseBlock, type SettingsType } from '../types/api.types'
import ContactFooter from '../components/ui/ContactFooter.vue'
import UiImage from '../components/ui/ui-image/UiImage.vue'
import CaseCarousel from '../components/ui/CaseCarousel.vue'
import LogoIcon from '../components/icons/LogoIcon.vue'
import { caseLayouts } from '../data/case-layouts'

const props=defineProps<{previewProject?:SettingsType['projects'][number]['items'][number];previewLanguage?:string}>()
const emit=defineEmits<{selectBlock:[id:string]}>()
const languageIso=()=>props.previewLanguage||getLanguageIso()
const route=useRoute(),router=useRouter(),projects=ref<SettingsType['projects'][number]>(),currentProject=ref<SettingsType['projects'][number]['items'][number]>(),currentIndex=ref(-1)
const editorial=computed(()=>{const p=currentProject.value;return caseLayouts[(p?.info.link||'').includes('relap.io')||/^(relap|релап)(\.io)?$/i.test(p?.info.title||'')?'relap':'']})
const isVideoSource=(value:string)=>/\.(mp4|webm|mov|m4v)(?:[?#]|$)/i.test(value)||/vimeo\.com|youtube\.com|youtu\.be/i.test(value)
const legacyBlocks=computed<CaseBlock[]>(()=>{const p=currentProject.value;if(!p)return[];const result:CaseBlock[]=[];if(editorial.value){editorial.value.sections.forEach((section,index)=>result.push({id:'legacy-carousel-'+index,type:'carousel',title:section.title,images:section.images}));result.push({id:'legacy-numbers',type:'numbers',title:'Numbers',items:editorial.value.numbers})}else{const media=p.info.images.slice(1).map(image=>image.link),images=media.filter(image=>!isVideoSource(image)),videos=media.filter(image=>isVideoSource(image));if(images.length)result.push({id:'legacy-carousel',type:'carousel',images});videos.forEach((video,index)=>result.push({id:'legacy-video-'+index,type:'video',video}))}const copyBlocks=p.details.content.slice(1);for(let index=0;index<copyBlocks.length;index++){const content=copyBlocks[index],title=content.title.toLowerCase(),next=copyBlocks[index+1],isTeam=title.includes('team')||title.includes('команд');if(isTeam&&next&&(next.title.toLowerCase().includes('thank')||next.title.toLowerCase().includes('благодар'))){result.push({id:'legacy-credits-'+index,type:'team-thanks',title:content.title,text:content.text,secondaryTitle:next.title,secondaryText:next.text});index++;continue}result.push({id:'legacy-copy-'+index,type:title.includes('thank')||title.includes('благодар')?'thanks':isTeam?'team':'text',title:content.title,text:content.text})}return result})
const normalizeBlocks=(items:CaseBlock[])=>items.flatMap(block=>{if(block.type!=='carousel'||!block.images?.length)return[block];const images=block.images.filter(image=>!isVideoSource(image)),videos=block.images.filter(image=>isVideoSource(image));return[...(images.length?[{...block,images}]:[]),...videos.map((video,index)=>({id:`${block.id}-video-${index}`,type:'video' as const,title:'',video}))]})
const blocks=computed(()=>normalizeBlocks(currentProject.value?.details.blocks ?? legacyBlocks.value).filter(block=>!block.hidden))
const caseTags=computed(()=>{
  const details=currentProject.value?.details
  const configured=[details?.industry||'',...(details?.tags||[])]
  const labels=configured.some(label=>label.trim())?configured:(editorial.value?.tags||[])
  const seen=new Set<string>()
  return labels.flatMap(label=>label.split(/[,;\n]/)).map(label=>label.trim()).filter(label=>{
    const key=label.normalize('NFKC').replace(/\s+/g,' ').toLowerCase()
    if(!key||seen.has(key))return false
    seen.add(key)
    return true
  })
})
const projectLink=computed(()=>{
  const value=currentProject.value?.info.link?.trim()
  if(!value)return undefined
  try { const url=new URL(value);return ['https:','http:'].includes(url.protocol)?url.href:undefined } catch { return undefined }
})
const videoEmbedUrl=(value:string)=>{if(/player\.vimeo\.com\/video\//i.test(value))return value;const vimeo=value.match(/(?:vimeo\.com\/|vimeo\.com\/video\/)(\d+)/i);if(vimeo)return`https://player.vimeo.com/video/${vimeo[1]}`;const youtube=value.match(/(?:youtube\.com\/(?:watch\?v=|embed\/)|youtu\.be\/)([\w-]+)/i);return youtube?`https://www.youtube.com/embed/${youtube[1]}`:''}
const isVideoEmbed=(value:string)=>!!videoEmbedUrl(value)
const changeAppColor=(background='inherit',color='inherit')=>{const app=props.previewProject?null:document.querySelector('#app') as HTMLElement|null;if(app){app.style.backgroundColor=background;app.style.color=color}}
const adjacent=(direction:-1|1)=>{if(!projects.value)return;for(let i=currentIndex.value+direction;i>=0&&i<projects.value.items.length;i+=direction){if(projects.value.items[i].rules.details&&!projects.value.items[i].rules.nda)return{project:projects.value.items[i],index:i}}}
const previousProject=computed(()=>adjacent(-1)),nextProject=computed(()=>adjacent(1))
const isLightBackground=computed(()=>{const hex=currentProject.value?.details.theme.background||'#000000';const raw=hex.replace('#','');const normalized=raw.length===3?raw.split('').map(char=>char+char).join(''):raw;if(!/^[0-9a-f]{6}$/i.test(normalized))return false;const [r,g,b]=[0,2,4].map(offset=>parseInt(normalized.slice(offset,offset+2),16)/255).map(value=>value<=.04045?value/12.92:((value+.055)/1.055)**2.4);return .2126*r+.7152*g+.0722*b>.45})
const accentText=computed(()=>{const raw=(currentProject.value?.details.theme.accentColor||editorial.value?.accent||'#777').replace('#','');const hex=raw.length===3?raw.split('').map(c=>c+c).join(''):raw;if(!/^[0-9a-f]{6}$/i.test(hex))return '#fff';const [r,g,b]=[0,2,4].map(i=>parseInt(hex.slice(i,i+2),16)/255).map(c=>c<=.04045?c/12.92:((c+.055)/1.055)**2.4);return .2126*r+.7152*g+.0722*b>.179?'#111':'#fff'})
const load=()=>{if(props.previewProject){currentProject.value=props.previewProject;return}projects.value=getData('projects') as SettingsType['projects'][number];const id=projectIndex(String(route.params.id)),project=projects.value.items[id],hasNdaAccess=!project?.rules.nda||sessionStorage.getItem(`nda-access:${languageIso()}:${id}`)==='granted';if(Number.isInteger(id)&&project?.rules.details&&hasNdaAccess){currentIndex.value=id;currentProject.value=project;if(route.path!==projectPath(id))router.replace(projectPath(id))}else{currentProject.value=undefined;router.replace('/works')}}
watch(()=>[route.params.id,props.previewProject],load,{immediate:true,deep:true});
const applyTheme=()=>{
  const theme=currentProject.value?.details.theme;
  if(theme)changeAppColor(theme.background||'#000',theme.textColor||'#fff');
};
// Dispose the previous theme before mounting its replacement (including language changes).
onBeforeUnmount(()=>changeAppColor());
onMounted(applyTheme);
watch(()=>currentProject.value?.details.theme,applyTheme,{flush:'post'});
</script>
<template>
  <main v-if="currentProject" class="case" :class="{'case--light-background':isLightBackground}" :style="{backgroundColor:currentProject.details.theme.background||'#000',color:currentProject.details.theme.textColor||'#fff','--accent':currentProject.details.theme.accentColor||editorial?.accent||'#777','--accent-text':accentText,'--case-background':currentProject.details.theme.background||'#000'}">
    <section class="case-hero contained" @click="props.previewProject&&emit('selectBlock','hero')">
      <h1 class="case-title" :class="{'case-title--accessible':!(currentProject.rules.showTitle??Boolean(currentProject.info.logo))}"><img v-if="(currentProject.rules.showTitle??Boolean(currentProject.info.logo))&&currentProject.info.logo" class="case-logo" :src="resolveMediaUrl(currentProject.info.logo)" :alt="currentProject.info.title"><span v-else>{{currentProject.info.title}}</span></h1>
      <p v-if="currentProject.details.content[0]" class="case-description" v-html="richText(currentProject.details.content[0].text)"/>
      <div v-if="currentProject.info.year || caseTags.length || projectLink" class="case-tags"><span v-if="currentProject.info.year" class="case-tag--accent">{{currentProject.info.year}}</span><span v-for="(tag,index) in caseTags" :key="tag" :class="{'case-tag--accent':index===0}">{{tag}}</span><a v-if="projectLink" class="case-tag-link" :href="projectLink" target="_blank" rel="noopener noreferrer">{{languageIso()==='ru'?'На сайт':languageIso()==='sr'?'Веб-сајт':'Website'}}<i aria-hidden="true"/></a></div>
    </section>
    <div v-for="block in blocks" :key="block.id" class="case-block-slot" @click="props.previewProject&&emit('selectBlock',block.id)" :style="block.spacing===undefined?undefined:{marginBottom:block.spacing+'px'}">
      <section v-if="block.type==='heading'" :data-block-type="block.type" class="case-block contained"><h2>{{block.title}}</h2></section>
      <section v-else-if="block.type==='carousel'" :data-block-type="block.type" class="case-block case-block--full"><h2 v-if="block.title" class="contained">{{block.title}}</h2><CaseCarousel v-if="block.images?.length" :images="block.images" :label="block.title||currentProject.info.title"/></section>
      <section v-else-if="block.type==='video'" :data-block-type="block.type" class="case-block contained"><h2 v-if="block.title">{{block.title}}</h2><iframe v-if="block.video&&isVideoEmbed(block.video)" class="video-embed" :src="videoEmbedUrl(block.video)" :title="block.title||'Video'" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen/><video v-else class="single-media" :src="resolveMediaUrl(block.video||'')" :poster="block.poster?resolveMediaUrl(block.poster):undefined" controls playsinline/></section>
      <section v-else-if="block.type==='image'" :data-block-type="block.type" class="case-block contained"><a class="media-original" :href="resolveMediaUrl(block.images?.[0]||'')" target="_blank" rel="noopener noreferrer" :aria-label="languageIso()==='ru'?'Открыть изображение в полном размере':'Open full-size image'"><img class="single-media" :src="resolveMediaUrl(block.images?.[0]||'')" :alt="block.alt||block.title||''"></a></section>
      <section v-else-if="block.type==='slides'" :data-block-type="block.type" class="case-block contained"><h2 v-if="block.title">{{block.title}}</h2><UiImage :images="block.images||[]" :gallery="true" :always-on="true"/></section>
      <section v-else-if="block.type==='gallery'" :data-block-type="block.type" class="case-block contained"><h2 v-if="block.title">{{block.title}}</h2><div class="gallery"><a v-for="(image,index) in block.images" :key="image+index" class="media-original" :href="resolveMediaUrl(image)" target="_blank" rel="noopener noreferrer"><img :src="resolveMediaUrl(image)" :alt="block.alt||block.title||currentProject.info.title"></a></div></section>
      <section v-else-if="block.type==='text-image'" :data-block-type="block.type" class="case-block contained split"><div><h2 v-if="block.title">{{block.title}}</h2><p v-html="richText((block.text||''))"/></div><a class="media-original" :href="resolveMediaUrl(block.images?.[0]||'')" target="_blank" rel="noopener noreferrer" :aria-label="languageIso()==='ru'?'Открыть изображение в полном размере':'Open full-size image'"><img class="single-media" :src="resolveMediaUrl(block.images?.[0]||'')" :alt="block.alt||block.title||''"></a></section>
      <section v-else-if="block.type==='numbers'" :data-block-type="block.type" class="case-block numbers contained"><h2 v-if="block.title">{{block.title}}</h2><div class="numbers-grid" :class="'numbers-grid--'+Math.min(block.items?.length||1,4)"><article v-for="item in block.items" :key="item.value"><strong>{{item.value}}</strong><p>{{item.text}}</p><small v-if="item.period" class="metric-context">{{item.period}}</small><small v-if="item.source" class="metric-context">{{item.source}}</small></article></div></section>
      <section v-else-if="block.type==='mentions'" :data-block-type="block.type" class="case-block mentions contained"><h2>{{block.title||(languageIso()==='ru'?'Упоминания в СМИ':'Mentions in the media')}}</h2><div class="mentions__list"><a v-for="(item,index) in block.items" :key="item.link||index" class="mentions__item" :href="item.link||undefined" target="_blank" rel="noopener noreferrer"><img v-if="item.image" class="mentions__logo" :src="resolveMediaUrl(item.image)" alt=""><span>{{item.text}}</span><i class="mentions__arrow" aria-hidden="true"/></a></div></section>
      <section v-else-if="block.type==='text-text'||block.type==='team-thanks'" :data-block-type="block.type" class="case-block credits contained" :class="{'credits--thanks':block.type==='team-thanks'}"><div><h2>{{block.title||(languageIso()==='ru'?'Команда':'Team')}}</h2><p v-html="richText((block.text||''))"/></div><div><h2>{{block.secondaryTitle||(languageIso()==='ru'?'Спасибо':'Thank you')}}</h2><p v-html="richText((block.secondaryText||''))"/></div></section>
      <section v-else-if="block.type==='text'||block.type==='team'||block.type==='thanks'" :data-block-type="block.type" class="case-block contained copy"><h2 v-if="block.title">{{block.title}}</h2><p v-html="richText((block.text||''))"/><div v-if="block.type==='team'&&block.items?.length" class="team-list"><p v-for="(person,index) in block.items" :key="index">{{person.text}}<small v-if="person.role">{{person.role}}</small></p></div></section>
      <section v-else-if="block.type==='iframe'" :data-block-type="block.type" class="case-block contained"><h2 v-if="block.title">{{block.title}}</h2><iframe v-if="embedSource(block.iframe)" class="embed" :src="embedSource(block.iframe)" sandbox="allow-scripts allow-popups allow-same-origin" referrerpolicy="no-referrer" :title="block.title||'Embedded content'" loading="lazy"/></section>
      <p v-if="block.caption" class="contained media-caption">{{block.caption}}</p>
    </div>
    <nav v-if="!props.previewProject" class="case-navigation"><button v-if="previousProject" class="case-navigation__previous" @click="router.push(projectPath(previousProject.index))"><i class="case-navigation__arrow case-navigation__arrow--left"/><span>{{previousProject.project.info.title}}</span></button><button class="case-home" aria-label="На главную" @click="router.push('/works')"><LogoIcon/></button><button v-if="nextProject" class="case-navigation__next" @click="router.push(projectPath(nextProject.index))"><span>{{nextProject.project.info.title}}</span><i class="case-navigation__arrow case-navigation__arrow--right"/></button></nav>
    <ContactFooter v-if="!props.previewProject"/>
  </main>
</template>
<style scoped lang="scss">
.case{--case-copy-width:670px;--case-grid-gutter:max(40px,calc((100% - var(--case-copy-width))/2));--case-radius:8px;min-width:0;min-height:100vh;width:100%;padding:24px 0 40px}
.case :is(h1,h2,p,span){color:inherit}.contained{width:var(--case-copy-width);max-width:calc(100% - 80px);margin-inline:auto;min-width:0}
.case-hero{margin-bottom:40px}.case-title{margin:0 0 32px;font-size:56px;line-height:64px;font-weight:400;overflow-wrap:anywhere}.case-logo{display:block;width:auto;height:64px;max-width:100%;object-fit:contain;object-position:left center}
.case-description,.copy p,.split p,.credits p,.numbers p{font-size:18px;line-height:28px;font-weight:400;margin:0}.case-description :deep(p+p),.copy :deep(p+p){margin-top:20px}
.case-tags{display:flex;flex-wrap:wrap;gap:8px;margin-top:16px}.case-tags :is(span,a){padding:4px 8px;border-radius:100px;background:rgba(255,255,255,.16);color:inherit;font-size:16px;line-height:24px}.case-tags .case-tag--accent{background:var(--accent);color:var(--accent-text,#fff)}
.case--light-background .case-tags :is(span,a):not(.case-tag--accent){background:rgba(0,0,0,.09);color:#222}
.case-tag-link{display:inline-flex;align-items:center;gap:4px;text-decoration:none}.case-tag-link i{width:16px;height:16px;background:currentColor;mask:url('/assets/icons/icon-ext-white.svg') center/contain no-repeat}
.case-block-slot{margin-bottom:48px}.case-block{min-width:0}.case-block h2{margin:0 0 28px;font-size:32px;line-height:40px;font-weight:400;letter-spacing:0}.case-block--full>h2.contained{width:var(--case-copy-width);max-width:calc(100% - 80px);margin-inline:auto}
.single-media,.video-embed,.embed{display:block;width:100%;border:0;border-radius:var(--case-radius);overflow:hidden}.single-media{height:auto}.video-embed{aspect-ratio:16/9;background:#000}.embed{min-height:60vh}.media-original{display:block;color:inherit;cursor:zoom-in}.gallery{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:20px}.gallery img{display:block;width:100%;border-radius:var(--case-radius)}
.split,.credits{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:20px;align-items:start}.split>*{min-width:0}
.numbers-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:20px;align-items:stretch}.numbers-grid--1{grid-template-columns:minmax(0,1fr)}.numbers article{min-width:0;padding:16px;border-radius:var(--case-radius);background:var(--accent);color:var(--accent-text,#fff);overflow-wrap:anywhere}.numbers strong{display:block;margin-bottom:8px;font-size:56px;line-height:64px;font-weight:400}.metric-context{display:block;font-size:14px;line-height:22px;margin-top:8px}
.mentions__list{display:grid;gap:20px}.mentions__item{display:grid;grid-template-columns:48px minmax(0,1fr) 32px;gap:16px;align-items:center;color:inherit;text-decoration:none;font-size:18px;line-height:28px;min-height:48px}.mentions__logo{width:48px;height:48px;border-radius:8px;object-fit:contain}.mentions__item>span{grid-column:2}.mentions__arrow{grid-column:3;width:32px;height:32px;border-radius:50%;background:rgba(255,255,255,.15);position:relative}.mentions__arrow:after{content:'';position:absolute;inset:6px;background:currentColor;mask:url('/assets/icons/icon-ext-white.svg') center/contain no-repeat}.case--light-background .mentions__arrow{background:rgba(0,0,0,.08)}
.team-list{display:grid;gap:16px;margin-top:16px}.team-list small{display:block;font-size:16px;line-height:24px;opacity:.8}.media-caption{font-size:16px;line-height:24px;margin-top:12px}
.case-navigation{display:grid;grid-template-columns:minmax(0,1fr) auto minmax(0,1fr);align-items:center;gap:8px;margin:48px 20px 0}.case-navigation button{display:flex;align-items:center;justify-content:center;gap:4px;height:32px;padding:0 8px;border:0;border-radius:100px;background:rgba(255,255,255,.15);color:inherit;font:inherit;font-size:16px;line-height:24px;cursor:pointer;transition:background-color .18s,color .18s}.case-navigation__previous{grid-column:1;justify-self:end}.case-navigation .case-home{grid-column:2;width:32px;padding:4px}.case-navigation__next{grid-column:3;justify-self:start}.case-navigation svg{width:24px;height:24px}.case--light-background .case-navigation button{background:rgba(0,0,0,.15)}.case-navigation button:hover{background:#fff;color:#000}.case-navigation button:focus-visible{outline:2px solid currentColor;outline-offset:3px}.case-navigation__arrow{display:block;width:20px;height:20px;flex:none;background:currentColor;mask:center/contain no-repeat}.case-navigation__arrow--left{mask-image:url('/assets/icons/arrow-left-white.svg')}.case-navigation__arrow--right{mask-image:url('/assets/icons/arrow-right-white.svg')}.case-tags .case-tag-link:hover{background:#fff;color:#000}.case--light-background .case-tags .case-tag-link:hover{background:#222;color:#fff}.case-tag-link{transition:background-color .18s,color .18s}.case-tag-link:focus-visible{outline:2px solid currentColor;outline-offset:3px}

.case :is(a,button):focus-visible{outline:2px solid currentColor;outline-offset:4px}.case-block :deep(.ui-image),.case-block :deep(.ui-image-container),.case-block :deep(.swiper){border-radius:var(--case-radius);overflow:hidden}
@container page (width < 1080px){.case{--case-copy-width:640px;--case-grid-gutter:40px}.case-title{font-size:48px;line-height:56px}}
@container page (width < 720px){.case{--case-copy-width:calc(100% - 40px);--case-grid-gutter:20px;padding-top:32px;padding-bottom:24px}.contained,.case-block--full>h2.contained{max-width:calc(100% - 40px)}.case-hero{margin-bottom:24px}.case-title{font-size:40px;line-height:48px;margin-bottom:40px}.case-logo{height:64px;max-width:100%}.case-description,.copy p,.split p,.credits p,.numbers p{font-size:16px;line-height:24px}.case-tags{gap:8px;margin-top:16px}.case-tags :is(span,a){font-size:14px;line-height:20px;padding:4px 8px}.case-block-slot{margin-bottom:32px}.case-block h2{font-size:24px;line-height:32px;margin-bottom:24px}.gallery,.split,.credits,.numbers-grid{grid-template-columns:minmax(0,1fr)}.credits{gap:32px}.numbers-grid{gap:20px}.numbers strong{font-size:32px;line-height:40px}.mentions__item{grid-template-columns:40px minmax(0,1fr) 24px;gap:12px;font-size:16px;line-height:24px}.mentions__logo{width:40px;height:40px}.mentions__arrow{width:24px;height:24px}.mentions__arrow:after{inset:2px}.case-navigation{margin-top:32px}.metric-context{font-size:14px;line-height:20px}}
.case-title--accessible{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip-path:inset(50%);white-space:nowrap}
</style>
